version: '3'
services:
  frontend:
    build:
      context: client
      dockerfile: Dockerfile
    container_name: yolo_frontend
    command: npm start
    expose:
      - 3000
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - 3000:3000
    stdin_open: true
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./backend:/app
      - ./app/node_modules
    container_name: yolo_backend
    command: npm start
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123
    ports:
      - 27017:27017
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db:
